version: "3.7"

services:
  # Diesen Block auskommentieren, um phpmyadmin nicht zu nutzen
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8086:80"
    links:
      - mysql:db
    restart: always

  mysql:
    image: mysql:latest
    # Credentials
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    # MySQL-Port
    ports:
      - "3308:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      # automatisches Importieren von allen Dumps in `mysql`
      - ./dumps/:/docker-entrypoint-initdb.d
    restart: always
